article/urls.py
from django.urls import path
from . import views

app_name = "article"
urlpatterns = [
    path("dashboard/",views.dashboard,name="dashboard"),
    path("addArticle/",views.addArticle,name="addArticle"),
    path("article/<int:id>",views.detail,name="detail"),
    path("update/<int:id>",views.updateArticle,name="update"),
    path("delete/<int:id>",views.deleteArticle,name="delete"),
    path("",views.articles,name="articles"),
    path("comment/<int:id>",views.addComment,name="comment"),
]

blog_django/urls.py
from django.contrib import admin
from django.urls import path,include
from article import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index,name="index"),
    path('about/', views.about,name="about"),
    path("articles/",include("article.urls")),
    path("user/",include("user.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views

app_name = "user"
urlpatterns = [
    path("login/",views.loginUser,name="login"),
    path("register/",views.registerUser,name="register"),
    path("logout/",views.logoutUser,name="logout"),
]

article/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.
class Article(models.Model):
    author = models.ForeignKey("auth.User", verbose_name="YAZAR", on_delete=models.CASCADE)
    title = models.CharField(verbose_name="BAŞLIK",max_length=50)
    content = RichTextField()
    created_date = models.DateField(verbose_name="OLUŞTURMA TARİHİ",auto_now_add=True)
    article_image = models.FileField(blank= True, null=True,verbose_name="")
    def __str__(self):
        return self.title
    class Meta:
        ordering = ['-created_date']
    

class Comment(models.Model):
    article = models.ForeignKey(Article,verbose_name="Makale",on_delete=models.CASCADE,related_name="comments")
    comment_author = models.CharField(max_length=50,verbose_name="İsim")
    comment_content = models.CharField(max_length=300,verbose_name="Yorum ")
    comment_date = models.DateField(auto_now_add=True)
    def __str__(self) -> str:
        return self.comment_author
    class Meta:
        ordering = ['-comment_date']

user/models.py
from django.db import models

# Create your models here.

article/forms.py
from django import forms
from .models import Article


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title','content','article_image']

user/forms.py
from django import forms 


class RegisterForm(forms.Form):
    username = forms.CharField(max_length=30, label="UserName")
    email = forms.EmailField(max_length=70,label="Email",widget=forms.EmailInput)
    password = forms.CharField(max_length=30,label="Password",widget=forms.PasswordInput)
    password_confirm = forms.CharField(max_length=30,label="Password Confirm",widget=forms.PasswordInput)

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        password_confirm = self.cleaned_data.get("password_confirm")
        email = self.cleaned_data.get("email")

        if username and password and password != password_confirm:
            raise forms.ValidationError("Parola eşleşmiyor")
        
        values = {
            "username": username,
            "password": password,
            "email": email
        }
        return values
    

class LoginForm(forms.Form):
    username = forms.CharField(max_length=30, label="UserName")
    password = forms.CharField(max_length=30,label="Password",widget=forms.PasswordInput)

article/views.py
from django.shortcuts import render,redirect,HttpResponse,get_object_or_404,reverse
from .forms import ArticleForm
from .models import Article,Comment
from django.contrib import messages
from django.contrib.auth.decorators import login_required
# Create your views here.

def index(request):
    return render(request,"index.html")

def about(request):
    return render(request,"about.html")

def articles(request):
    keyword = request.GET.get("keyword")
    if keyword:

        articles = Article.objects.filter(title__contains = keyword)
        return render(request,"articles.html",{"articles":articles})
    
    articles = Article.objects.all()

    return render(request,"articles.html",{"articles":articles})

@login_required(login_url="user:login")
def dashboard(request):
    articles = Article.objects.filter(author = request.user)
    context = {
        "articles":articles
    }
    return render(request,"dashboard.html",context)
@login_required(login_url="user:login")
def addArticle(request):
    form = ArticleForm(request.POST or None,request.FILES or None)
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()
        messages.success(request,"Makale başarıyla oluşturuldu.")
        return redirect('article:dashboard')
    return render(request,"addArticle.html",{"form": form})


def detail(request,id):
    #*article = Article.objects.filter(id=id).first()
    article = get_object_or_404(Article,id=id)

    comments = article.comments.all()
    
    
    return render(request,"detail.html",{"article":article,"comments":comments})

@login_required(login_url="user:login")
def updateArticle(request,id):
    article = get_object_or_404(Article,id= id)
    form = ArticleForm(request.POST or None, request.FILES or None, instance=article)

    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()
        
        messages.success(request,"Makale başarıyla güncellendi.")
        return redirect('article:dashboard')
    return render(request,"update.html",{"form":form})

@login_required(login_url="user:login")
def deleteArticle(request,id):
    article = get_object_or_404(Article,id= id)
    article.delete()

    messages.success(request,"Makale başarıyla silindi.")
    return redirect('article:dashboard')

@login_required(login_url="user:login")
def addComment(request,id):
    article= get_object_or_404(Article,id=id)

    if request.method =="POST":
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")
        
        newComment = Comment(comment_author= comment_author, comment_content=comment_content)
        newComment.article = article
        newComment.save()
    return redirect(reverse("article:detail",kwargs={"id":id}))

user/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login,authenticate, logout
from .forms import RegisterForm,LoginForm
from django.contrib.auth.models import User
from django.contrib import messages

# Create your views here.

def loginUser(request):
    form = LoginForm(request.POST or None)
    context = {
        "form": form
    }
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        user = authenticate(username=username, password= password)
        if user is None:
            messages.info(request,"Kullanıcı adı veya şifre hatalı",extra_tags="danger")
            return render(request,'login.html',context)
        messages.success(request,"Giriş Başarılı")
        login(request,user)
        return redirect('index')
    return render(request,'login.html',context)

def registerUser(request):

    form = RegisterForm(request.POST or None)
    context = {
        "form": form
    }
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        email = form.cleaned_data.get("email")

        
        if User.objects.filter(username=username).exists():
            messages.info(request,"Kullanıcı adı sistemde zaten kayıtlı",extra_tags="warning")
            return render(request,'register.html',context)

        user = User.objects.create_user(username = username,email = email,password=password)
        login(request,user)
        messages.success(request,"Başarıyla kayıt oldunuz")
        return redirect('index')
    
    return render(request,'register.html',context)



def logoutUser(request):
    logout(request)
    messages.success(request,"Başarıyla çıkış yapıldı")
    return redirect('index')

templates/about.html
{% extends "layout.html" %}

{% block body %}
<div class="container">
    <h3>HAKKIMDA</h3>
    <hr>

    Ben, yaratıcı ve meraklı bir kişilik olarak kendimi görüyorum. Yeni şeyler öğrenmeyi ve keşfetmeyi seven biriyim. 
    Empati yeteneğim güçlüdür; çevremdeki insanların duygularını anlamak ve onlara destek olmak benim için önemlidir. 
    Geniş bir ilgi alanım var; kültürel etkinlikler ve sanatsal faaliyetlerle ilgilenmekten keyif alıyorum. 
    Duygusal olarak derin ve düşünceliyim; iç dünyamdaki karmaşık duyguları işlemek ve anlamak benim için doğal bir süreçtir. 
    Sabırlı ve kararlı biriyim; hedeflerime ulaşmak için uzun vadeli düşünür ve çaba gösteririm. Mizah anlayışım kuvvetlidir ve çevremdekileri güldürmekten hoşlanırım.
    Yaratıcılığımı farklı alanlarda ifade etmeye eğilimliyim; sanat, yazı, müzik gibi alanlarda yeteneklerim bulunmaktadır. 
    İçsel bir araştırmacıyım; dünyayı ve toplumu anlamak için sürekli olarak sorular sorar ve bilgi edinmeye çalışırım. 
    Değişime açık bir insanım; yeni deneyimlere ve fikirlere karşı önyargısız bir şekilde yaklaşırım. 
    Yakın çevremde, dürüstlüğüm, sadakatim ve güvenilirliğimle tanınırım; çünkü benim için değerli olan ilişkilerim benim için her şeyden önce gelir.
    <hr>
</div>

{% endblock %}

templates/addArticle.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}

{% block body %}
<div class="row" >
    <div class="col-md-6 offset-md-3">
        <h3>Makale Oluştur</h3>
        <hr>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy }}
            <button type= "submit" class="btn btn-primary">Kaydet</button>
        </form>
    </div>
</div>
{% endblock body %}

templates/articles.html
{% extends "layout.html" %}

{% block body %}
<div class="row">
    <div class="col-md-10 offset-md-3">
        <div class="col-lg-8">
            <h3>MAKALELER</h3><hr>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-10 offset-md-3">
        <div class="col-lg-8">
            <form >
                {% csrf_token %}
                <input class="form-control mr-sm-2" type="search" placeholder="Makale Ara" name="keyword">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Ara</button>
            </form>
        </div>
    </div>
</div>
{% if articles %}
{% for article in articles %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-10 offset-md-3">
            <div class="col-lg-8">
            <!-- Post content-->
                <article>
                <!-- Post header-->
                    <header class="mb-4">
                    <!-- Post title-->
                        <a href="/articles/article/{{article.id}}"><h2 class="fw-bolder mb-1">{{article.title}}</h2></a>
                    <!-- Post meta content-->
                        <div class="text-muted fst-italic mb-2">Posted on {{article.created_date}} by {{article.author.username}}</div>
                    
                    </header>
                <!-- Preview image figure-->
                    {% if article.article_image %}
                    <a href="{% url 'article:detail' article.id %}"><figure class="mb-4"><img class="img-fluid rounded" src="{{article.article_image.url}}" alt="..." /></figure></a>
                    {% endif %}
                <!-- Post content-->
                    <section class="mb-5">
                        <p class="fs-5 mb-4">{{article.content|safe|truncatewords:10}}</p>
                        <a style="float: right;" href= "{% url 'article:detail' article.id %}">Devamını Oku</a>
                        <hr>
                    </section>
                </article>
            <!-- Comments section-->
            </div>
        </div>     
    </div>
</div>

{% endfor %}
{% else %}
<div class="row">
    <div class="col-md-10 offset-md-3">
        <div class="col-lg-8">  
            <div class=" alert alert-danger">Makale bulunamadı.</div>
        </div>
    </div>
</div>
{% endif %}
{% endblock body %}

templates/dashboard.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}

{% block body %}

<div class="row" >
    <div class="col-md-6 offset-md-3">
        <h3>Makale Oluştur</h3>
        <hr>
        {% if request.user.is_authenticated %}
        <h6>Hosgeldiniz <small>{{request.user.username}}</small></h6>
        
        {% else %}
        {% endif %}
        <form method="POST">
            {% csrf_token %}
            {{form|crispy }}
            <a href="{% url 'article:addArticle' %}" class="btn btn-danger">Makale Oluştur</a>
        </form>
  
    </div>    
    {% if articles %}
<table class="table table-dark">
    <thead>
      <tr>
        <th scope="col">id</th>
        <th scope="col">BAŞLIK</th>
        <th scope="col">YAZAR</th>
        <th scope="col">OLUŞTURMA TARİHİ</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
        {% for article in articles %}
        <tr>
            <th scope="row">{{article.id}}</th>
            <td><a href="{% url 'article:detail' article.id %}">{{article.title}}</a></td>
            <td>{{article.author.username}}</td>
            <td>{{article.created_date}}</td>
            <td><a href="{% url 'article:update' article.id %}" class ="btn btn-warning">Update<a/></td>
            <td><a href="{% url 'article:delete' article.id %}" class = "btn btn-danger">Delete<a/></td>
            
          </tr>

        
        {% endfor %}
      
      
    </tbody>
  </table>

{% else %}
<div class=" alert alert-danger">Makale bulunamadı.</div>
{% endif %}
</div>


{% endblock body %}

templates/detail.html
{% extends "layout.html" %}
{% load static %}
{% block body %}
<div class="container mt-5">
    <div class="row">
        <div class="col-lg-8">
            <!-- Post content-->
            <article>
                <!-- Post header-->
                <header class="mb-4">
                    <!-- Post title-->
                    <h2 class="fw-bolder mb-1">{{article.title}}</h2>
                    <!-- Post meta content-->
                    <div class="text-muted fst-italic mb-2">Posted on {{article.created_date}} by {{article.author.username}}</div>
                    
                </header>
                <!-- Preview image figure-->
                {% if article.article_image %}
                <figure class="mb-4"><img class="img-fluid rounded" src="{{article.article_image.url}}" alt="..." /></figure>
                {% endif %}
                <!-- Post content-->
                <section class="mb-5">
                    <p class="fs-5 mb-4">{{article.content|safe}}</p>
                    
                </section>
            </article>
            <!-- Comments section-->
            <section class="mb-5">
                <div class="card bg-light">
                    <h5 class="card-header">Leave a comment</h5>
                    <div class="card-body">
                        <!-- Comment form-->
                        <form method= "POST" action= "{% url 'article:comment' article.id %}" class="mb-4">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="formGroupExampleInput">Name</label>
                                <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Enter name" name="comment_author">
                            </div>
                            <div class="form-group">
                    
                                <label for="formGroupExampleInput">Comment</label>    
                                <textarea name="comment_content" class="form-control" rows="3" placeholder="Join the discussion and leave a comment!"></textarea>
                            </div>
                            <div class="mb-5">

                                <div class="card bg-light">
                                    <button type="submit" class="btn btn-primary">Add Comment</button>
                                
                                </div>
                            </div>
                        </form>
                        <!-- Comment with nested comments-->
                        <h4>Yorumlar</h4>
                        <hr>
                        {% if comments %}
                            {% for comment in comments  %}
                            
                            
                            <div class="d-flex mb-4">
                                <!-- Parent comment-->
                                <div class="flex-shrink-0"><img class="rounded-circle" src="{% static 'images/usr.png' %}" alt="..."  width= "100" height= "50"></div>
                                <div class="ms-3">
                                    <div class="fw-bold">{{comment.comment_author}}</div>
                                        {{comment.comment_date}}<br>
                                        {{comment.comment_content}}
                                    
                                    
                                </div>
                            </div>
                            {% endfor %}
                        {% else %}
                        <div class=" alert alert-danger">Henüz yorum yok.</div>
                        {% endif %}
                        
                        
                    </div>
                </div>
            </section>
        </div>
    </div>     
</div>

{% endblock body %}

templates/includes/navbar.html
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="/">BLOG RPOJESİ</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample03" aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExample03">
      <ul class="navbar-nav mr-auto">

        <li class="nav-item active">
          <a class="nav-link" href="{% url 'about' %}">Hakkımızda</a>
        </li>

        <li class="nav-item active">
          <a class="nav-link" href="{% url 'article:articles' %}">Makaleler</a>
        </li>
      </ul>
      
      <ul class="navbar-nav ml-auto">
        {% if request.user.is_authenticated %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'article:dashboard' %}">Kontrol Paneli</a>
        </li>

        <li class="nav-item active">
          <a class="nav-link" href="{% url 'user:logout' %}">Çıkış Yap</a>
        </li>
        
        {% else %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'user:login' %}">Giriş Yap</a>
        </li>

        {% endif %}

        <li class="nav-item active">
          <a class="nav-link" href="{% url 'user:register' %}">Kayıt Ol</a>
        </li>
      </ul>
      
    </div>
  </nav>

templates/index.html
{% extends "layout.html" %}

{% block body %}


<div class="jumbotron text-center">
    <h3>Bloğuma Hoşgeldiniz</h3>
    <p>Bu blogta geliştiriciler olarak blog yazılarınızı paylaşabilirsiniz ve insanlara yardımcı olabilirsiniz.</p> 

</div>

{% endblock %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    
    <title>BLOG PROJESİ</title>
    
</head>

<body>
    
    {% include "includes/navbar.html" %}

    
    <div style="margin-top: 50px; margin-bottom: 100px;" class="container">
        {% if messages %}
        {% for message in messages %}
        
        <div class=" alert alert-{{message.tags}}">{{ message }}</div>
        
        {% endfor %}
        
        {% endif %}
        
    </div>
    
    {% block body %}
   
    {% endblock body %}
    
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>
    </body>
</html>

templates/login.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}

{% block body %}

<div class="row" >
    <div class="col-md-6 offset-md-3">
        <h3>Sign in</h3>
        <hr>
        <form method="POST">
            {% csrf_token %}
            {{form|crispy }}
            <button type= "submit" class="btn btn-primary">Sign in</button>
        </form>
    </div>
</div>

{% endblock body %}

templates/register.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}

{% block body %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Register</h3>
        <hr>
        <form method="POST">
            {% csrf_token %}
            {{form|crispy }}
            <button type="submit" class="btn btn-primary">Register</button>
        </form>
    </div>
</div>
{% endblock body %}

templates/update.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}

{% block body %}
<div class="row" >
    <div class="col-md-6 offset-md-3">
        <h3>Makale Güncelle</h3>
        <hr>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy }}
            <button type= "submit" class="btn btn-primary">Kaydet</button>
        </form>
    </div>
</div>
{% endblock body %}